#define AA_BUTTON_X_LEFT 965
#define AA_BUTTON_X_RIGHT 984
#define AA_BUTTON_Y_UP 33
#define AA_BUTTON_Y_DOWN 52
#define AB_BUTTON_X_LEFT 965
#define AB_BUTTON_X_RIGHT 984
#define AB_BUTTON_Y_UP 52
#define AB_BUTTON_Y_DOWN 71